### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by itz-shyam** [Python3-8/Riverr#1]
fk u

**Comment by Python3-8** [comment]
Closing as this issue is inappropriate and unclear. If you disagree, feel free to post another comment and I will reopen this issue.

**Comment by itz-shyam** [comment]
@Python3-8 lol u act as such u own a very famous repo

**Comment by Python3-8** [comment]
Lolz but really I don't want cussing on my repo

**Comment by Python3-8** [comment]
U there bruh?

**Comment by Python3-8** [comment]
Bro I replied literally 17 seconds after you did

[![image.png](https://i.postimg.cc/28Lkjf0w/image.png)](https://postimg.cc/w7H8Fn8y)

**Comment by itz-shyam** [comment]
I meant the comment Sent from Mail for Windows 10 From: Pranav PooruliSent: Wednesday, August 4, 2021 9:43 AMTo: Python3-8/RiverrCc: itz-shyam; AuthorSubject: Re: [Python3-8/Riverr] bruh (#1) Bro I replied literally 17 seconds after you did—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Python3-8** [comment]
Um wut dat

**Comment by itz-shyam** [comment]
i sent it from email so..

**Comment by itz-shyam** [comment]
i said that in the comments u act as a famous repo owner
